In [2]:
import numpy as np
list1 = [ 1, 2, 3, 4]
arr = np.array( list1 )
type( arr )

numpy.ndarray

In [6]:
a = np.arange( 0, 10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
b = np.arange(0, 10, 2)
b

array([0, 2, 4, 6, 8])

In [3]:
np.zeros( (5, 5) )

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
np.ones( (2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.random.randint( 0, 100 )

46

In [11]:
np.random.randint( 0, 100, (5, 5))

array([[90, 74, 55, 87, 72],
       [60, 58, 41, 71, 83],
       [36, 99, 21, 52, 47],
       [ 0, 60,  4, 50, 51],
       [ 1, 63, 66, 13, 60]])

In [12]:
np.linspace(0, 10, 6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [14]:
np.linspace(0, 10, 101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [18]:
np.random.seed( 101 )
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [28]:
data = np.random.randint(0, 100, 10)
print( data )
print( f'max: {data.max()}' )
print( f'min: {data.min()}' )
print( f'mean: {data.mean()}' )
print( f'argmax: {data.argmax()}' ) # argmax is get the location of maximum value 
print( f'argmin: {data.argmin()}' ) # argmax is get the location of minimum value 

[71 68 23 35 79 98 67 82 57 77]
max: 98
min: 23
mean: 65.7
argmax: 5
argmin: 2


In [34]:
# using numpy arange() function cooperated with reshape() to generate 2D matrix
mat = np.arange( 0, 100).reshape( 10, 10)
print( mat, "\n" )
print( mat[:, 2], "\n")
print( mat[3, :], "\n")
print( mat > 50, '\n')
print( mat[mat > 50], '\n')

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]] 

[ 2 12 22 32 42 52 62 72 82 92] 

[30 31 32 33 34 35 36 37 38 39] 

[[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True 